name: Docker Image CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Java dep setup
              uses: actions/setup-java@v3
              with:
                  distribution: "temurin"
                  java-version: "17"

            - name: Build Backend
              run: mvn -B package --file ./backend/pom.xml

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Conditional Docker Build and push
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              run: |
                  docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/kaardirakendus:latest -f ./Dockerfile .
                  docker push ${{ secrets.DOCKERHUB_USERNAME }}/kaardirakendus:latest

            #- name: Build and push to Docker
            #  uses: docker/build-push-action@v5
            #  with:
            #      context: .
            #      file: ./Dockerfile
            #      push: true
            #      tags: ${{ secrets.DOCKERHUB_USERNAME }}/kaardirakendus:latest
